### ISSUE TITLE
Error prone compile error with using IntelliJ

### ISSUE THREAD

**Issue by jiachen1120** [networknt/light-4j#471]
@BalloonWen and I encounter the same issue after updating the version to 1.6.1-SNAPSHOT

The error message is shown below:

Error:java: java.lang.RuntimeException: java.lang.NoSuchMethodError: com.sun.tools.javac.util.JavacMessages.add(Lcom/sun/tools/javac/util/JavacMessages$ResourceBundleHelper;)V
Error:java: Caused by: java.lang.NoSuchMethodError: com.sun.tools.javac.util.JavacMessages.add(Lcom/sun/tools/javac/util/JavacMessages$ResourceBundleHelper;)V
Error:java: 	at com.google.errorprone.BaseErrorProneJavaCompiler.setupMessageBundle(BaseErrorProneJavaCompiler.java:202)
Error:java: 	at com.google.errorprone.ErrorProneJavacPlugin.init(ErrorProneJavacPlugin.java:40)

After commenting out the plugin, the compiler can work properly

**Comment by noahwolf2001** [comment]
ok ill help you on 18:00 or 5:00 Pm Okay. thats when im avaliable

**Comment by stevehu** [comment]
I just made sure that it could be compiled with the Maven and didn't realize that the IntelliJ IDEA is not working. @noahwolf2001 Since you know what is the issue, we will leave it to you to help. Thanks in advance.

**Comment by noahwolf2001** [comment]
sorry i didnt come at the desired time im here now

**Comment by noahwolf2001** [comment]
thanks steve but if you could see if the prox 15 would be available for me soon i'd appreciate the assistance of the server2server though

**Comment by stevehu** [comment]
@noahwolf2001 The server to server is a demo application I created years ago. It should be removed as the server to server communication can be done with the client module provided in light-4j. Take a look at this tutorial 

https://doc.networknt.com/tutorial/common/discovery/

**Comment by stevehu** [comment]
@noahwolf2001 Do you know what is the root cause that the new version of the error_prone_core is not working with IntelliJ IDEA?

**Comment by stevehu** [comment]
@jiachen1120 has found the IntelliJ IDEA plugin to resolve the issue. Here is the document on how to install the plugin. https://doc.networknt.com/tool/idea/errorprone-plugin/

**Comment by pli2014** [comment]
com.sun.tools.javac.util.JavacMessages: 
```

  @Override
    public void add(String bundleName) throws MissingResourceException {
        add(locale -> ResourceBundle.getBundle(bundleName, locale));
    }

    public void add(ResourceBundleHelper ma) {
        bundleHelpers = bundleHelpers.prepend(ma);
        if (!bundleCache.isEmpty())
            bundleCache.clear();
        currentBundles = null;
    }
```
the add method with lambda: 

  /** Registers our message bundle. */
  public static void setupMessageBundle(Context context) {
    ResourceBundle bundle = ResourceBundle.getBundle("com.google.errorprone.errors");
    JavacMessages.instance(context).add(l -> bundle);
  }

**Comment by stevehu** [comment]
@pli2014 We have removed the errorprone from the 2.0.x branch, and this issue is resolved already.
